const cards = {
  blue: {
      'Strike_B': 'strike.png',
      'All For One': 'all_for_one.png',
      'Ball Lightning': 'ball_lightning.png',
      'Barrage': 'barrage.png',
      'Beam Cell': 'beam_cell.png',
      'Blizzard': 'blizzard.png',
      'Claw': 'claw.png',
      'Cold Snap': 'cold_snap.png',
      'Compile Driver': 'compile_driver.png',
      'Core Surge': 'core_surge.png',
      'Doom and Gloom': 'doom_and_gloom.png',
      'FTL': 'ftl.png',
      'Go For The Eyes': 'go_for_the_eyes.png',
      'Hyper Beam': 'hyper_beam.png',
      'Lock On': 'lock_on.png',
      'Melter': 'melter.png',
      'Meteor Strike': 'meteor_strike.png',
      'Rebound': 'rebound.png',
      'Rip And Tear': 'rip_and_tear.png',
      'Scrape': 'scrape.png',
      'Steamline': 'steamline.png',
      'Sunder': 'sunder.png',
      'Sweeping Beam': 'sweeping_beam.png',
      'Thunder Strike': 'thunder_strike.png',
      'Biased Cognition': 'biased_cognition.png',
      'Buffer': 'buffer.png',
      'Capacitor': 'capacitor.png',
      'Creative AI': 'creative_ai.png',
      'Defragment': 'defragment.png',
      'Echo Form': 'echo_form.png',
      'Electrodynamics': 'electrodynamics.png',
      'Heatsinks': 'heatsinks.png',
      'Hello World': 'hello_world.png',
      'Lightning Mastery': 'lightning_mastery.png',
      'Loop': 'loop.png',
      'Machine Learning': 'machine_learning.png',
      'Storm': 'storm.png',
      'Static Discharge': 'static_discharge.png',
      'Self Repair': 'self_repair.png',
      'Aggregate': 'aggregate.png',
      'Amplify': 'amplify.png',
      'Auto Shields': 'auto_shields.png',
      'Boot Sequence': 'boot_sequence.png',
      'Chaos': 'chaos.png',
      'Charge Battery': 'charge_battery.png',
      'Chill': 'chill.png',
      'Consume': 'consume.png',
      'Coolheaded': 'coolheaded.png',
      'Darkness': 'darkness.png',
      'Defend_B': 'defend.png',
      'Double Energy': 'double_energy.png',
      'Dualcast': 'dualcast.png',
      'Equilibrium': 'equilibrium.png',
      'Fission': 'fission.png',
      'Force Field': 'force_field.png',
      'Fusion': 'fusion.png',
      'Genetic Algorithm': 'genetic_algorithm.png',
      'Glacier': 'glacier.png',
      'Hologram': 'hologram.png',
      'Leap': 'leap.png',
      'Multicast': 'multicast.png',
      'Overclock': 'overclock.png',
      'Rainbow': 'rainbow.png',
      'Reboot': 'reboot.png',
      'Recursion': 'recursion.png',
      'Recycle': 'recycle.png',
      'Reinforced Body': 'reinforced_body.png',
      'Reprogram': 'reprogram.png',
      'Seek': 'seek.png',
      'Skim': 'skim.png',
      'Stack': 'stack.png',
      'Steam Barrier': 'steam_barrier.png',
      'Tempest': 'tempest.png',
      'Turbo': 'turbo.png',
      'White Noise': 'white_noise.png',
      'Zap': 'zap.png',
      
      // UPGRADED BELOW
      'Strike_B+1': 'strike.png',
      'All For One+1': 'all_for_one.png',
      'Ball Lightning+1': 'ball_lightning.png',
      'Barrage+1': 'barrage.png',
      'Beam Cell+1': 'beam_cell.png',
      'Blizzard+1': 'blizzard.png',
      'Claw+1': 'claw.png',
      'Cold Snap+1': 'cold_snap.png',
      'Compile Driver+1': 'compile_driver.png',
      'Core Surge+1': 'core_surge.png',
      'Doom and Gloom+1': 'doom_and_gloom.png',
      'FTL+1': 'ftl.png',
      'Go For The Eyes+1': 'go_for_the_eyes.png',
      'Hyper Beam+1': 'hyper_beam.png',
      'Lock On+1': 'lock_on.png',
      'Melter+1': 'melter.png',
      'Meteor Strike+1': 'meteor_strike.png',
      'Rebound+1': 'rebound.png',
      'Rip And Tear+1': 'rip_and_tear.png',
      'Scrape+1': 'scrape.png',
      'Steamline+1': 'steamline.png',
      'Sunder+1': 'sunder.png',
      'Sweeping Beam+1': 'sweeping_beam.png',
      'Thunder Strike+1': 'thunder_strike.png',
      'Biased Cognition+1': 'biased_cognition.png',
      'Buffer+1': 'buffer.png',
      'Capacitor+1': 'capacitor.png',
      'Creative AI+1': 'creative_ai.png',
      'Defragment+1': 'defragment.png',
      'Echo Form+1': 'echo_form.png',
      'Electrodynamics+1': 'electrodynamics.png',
      'Heatsinks+1': 'heatsinks.png',
      'Hello World+1': 'hello_world.png',
      'Lightning Mastery+1': 'lightning_mastery.png',
      'Loop+1': 'loop.png',
      'Machine Learning+1': 'machine_learning.png',
      'Storm+1': 'storm.png',
      'Static Discharge+1': 'static_discharge.png',
      'Self Repair+1': 'self_repair.png',
      'Aggregate+1': 'aggregate.png',
      'Amplify+1': 'amplify.png',
      'Auto Shields+1': 'auto_shields.png',
      'Boot Sequence+1': 'boot_sequence.png',
      'Chaos+1': 'chaos.png',
      'Charge Battery+1': 'charge_battery.png',
      'Chill+1': 'chill.png',
      'Consume+1': 'consume.png',
      'Coolheaded+1': 'coolheaded.png',
      'Darkness+1': 'darkness.png',
      'Defend_B+1': 'defend.png',
      'Double Energy+1': 'double_energy.png',
      'Dualcast+1': 'dualcast.png',
      'Equilibrium+1': 'equilibrium.png',
      'Fission+1': 'fission.png',
      'Force Field+1': 'force_field.png',
      'Fusion+1': 'fusion.png',
      'Genetic Algorithm+1': 'genetic_algorithm.png',
      'Glacier+1': 'glacier.png',
      'Hologram+1': 'hologram.png',
      'Leap+1': 'leap.png',
      'Multicast+1': 'multicast.png',
      'Overclock+1': 'overclock.png',
      'Rainbow+1': 'rainbow.png',
      'Reboot+1': 'reboot.png',
      'Recursion+1': 'recursion.png',
      'Recycle+1': 'recycle.png',
      'Reinforced Body+1': 'reinforced_body.png',
      'Reprogram+1': 'reprogram.png',
      'Seek+1': 'seek.png',
      'Skim+1': 'skim.png',
      'Stack+1': 'stack.png',
      'Steam Barrier+1': 'steam_barrier.png',
      'Tempest+1': 'tempest.png',
      'Turbo+1': 'turbo.png',
      'White Noise+1': 'white_noise.png',
      'Zap+1': 'zap.png',
  },
  green: {
    'Strike_G': 'strike.png',
    'A Thousand Cuts': 'a_thousand_cuts.png',
    'Accuracy': 'accuracy.png',
    'Acrobatics': 'acrobatics.png',
    'Adrenaline': 'adrenaline.png',
    'After Image': 'after_image.png',
    'Alchemize': 'alchemize.png',
    'All Out Attack': 'all_out_attack.png',
    'Backflip': 'backflip.png',
    'Backstab': 'backstab.png',
    'Bane': 'bane.png',
    'Blade Dance': 'blade_dance.png',
    'Blur': 'blur.png',
    'Bouncing Flask': 'bouncing_flask.png',
    'Bullet Time': 'bullet_time.png',
    'Burst': 'burst.png',
    'Calculated Gamble': 'calculated_gamble.png',
    'Caltrops': 'caltrops.png',
    'Catalyst': 'catalyst.png',
    'Choke': 'choke.png',
    'Cloak and Dagger': 'cloak_and_dagger.png',
    'Concentrate': 'concentrate.png',
    'Corpse Explosion': 'corpse_explosion.png',
    'Crippling Poison': 'crippling_poison.png',
    'Dagger Spray': 'dagger_spray.png',
    'Dagger Throw': 'dagger_throw.png',
    'Dash': 'dash.png',
    'Deadly Poison': 'deadly_poison.png',
    'Defend_G': 'defend.png',
    'Deflect': 'deflect.png',
    'Die Die Die': 'die_die_die.png',
    'Distraction': 'distraction.png',
    'Dodge and Roll': 'dodge_and_roll.png',
    'Doppelganger': 'doppelganger.png',
    'Endless Agony': 'endless_agony.png',
    'Envenom': 'envenom.png',
    'Escape Plan': 'escape_plan.png',
    'Eviscerate': 'eviscerate.png',
    'Expertise': 'expertise.png',
    'Finisher': 'finisher.png',
    'Flechettes': 'flechettes.png',
    'Flying Knee': 'flying_knee.png',
    'Footwork': 'footwork.png',
    'Glass Knife': 'glass_knife.png',
    'Grand Finale': 'grand_finale.png',
    'Heel Hook': 'heel_hook.png',
    'Infinite Blades': 'infinite_blades.png',
    'Leg Sweep': 'leg_sweep.png',
    'Malaise': 'malaise.png',
    'Masterful Stab': 'masterful_stab.png',
    'Neutralize': 'neutralize.png',
    'Nightmare': 'nightmare.png',
    'Noxious Fumes': 'noxious_fumes.png',
    'Outmaneuver': 'outmaneuver.png',
    'Phantasmal Killer': 'phantasmal_killer.png',
    'Piercing Wail': 'piercing_wail.png',
    'Poisoned Stab': 'poisoned_stab.png',
    'Predator': 'predator.png',
    'Prepared': 'prepared.png',
    'Quick Slash': 'quick_slash.png',
    'Reflex': 'reflex.png',
    'Riddle With Holes': 'riddle_with_holes.png',
    'Setup': 'setup.png',
    'Skewer': 'skewer.png',
    'Slice': 'slice.png',
    'Sneaky Strike': 'sneaky_strike.png',
    'Storm of Steel': 'storm_of_steel.png',
    'Sucker Punch': 'sucker_punch.png',
    'Survivor': 'survivor.png',
    'Tactician': 'tactician.png',
    'Terror': 'terror.png',
    'Tools of the Trade': 'tools_of_the_trade.png',
    'Unload': 'unload.png',
    'Well Laid Plans': 'well_laid_plans.png',
    'Wraith Form': 'wraith_form.png',

    // UPGRADED BELOW
    'Strike_G+1': 'strike.png',
    'A Thousand Cuts+1': 'a_thousand_cuts.png',
    'Accuracy+1': 'accuracy.png',
    'Acrobatics+1': 'acrobatics.png',
    'Adrenaline+1': 'adrenaline.png',
    'After Image+1': 'after_image.png',
    'Alchemize+1': 'alchemize.png',
    'All Out Attack+1': 'all_out_attack.png',
    'Backflip+1': 'backflip.png',
    'Backstab+1': 'backstab.png',
    'Bane+1': 'bane.png',
    'Blade Dance+1': 'blade_dance.png',
    'Blur+1': 'blur.png',
    'Bouncing Flask+1': 'bouncing_flask.png',
    'Bullet Time+1': 'bullet_time.png',
    'Burst+1': 'burst.png',
    'Calculated Gamble+1': 'calculated_gamble.png',
    'Caltrops+1': 'caltrops.png',
    'Catalyst+1': 'catalyst.png',
    'Choke+1': 'choke.png',
    'Cloak and Dagger+1': 'cloak_and_dagger.png',
    'Concentrate+1': 'concentrate.png',
    'Corpse Explosion+1': 'corpse_explosion.png',
    'Crippling Poison+1': 'crippling_poison.png',
    'Dagger Spray+1': 'dagger_spray.png',
    'Dagger Throw+1': 'dagger_throw.png',
    'Dash+1': 'dash.png',
    'Deadly Poison+1': 'deadly_poison.png',
    'Defend_G+1': 'defend.png',
    'Deflect+1': 'deflect.png',
    'Die Die Die+1': 'die_die_die.png',
    'Distraction+1': 'distraction.png',
    'Dodge and Roll+1': 'dodge_and_roll.png',
    'Doppelganger+1': 'doppelganger.png',
    'Endless Agony+1': 'endless_agony.png',
    'Envenom+1': 'envenom.png',
    'Escape Plan+1': 'escape_plan.png',
    'Eviscerate+1': 'eviscerate.png',
    'Expertise+1': 'expertise.png',
    'Finisher+1': 'finisher.png',
    'Flechettes+1': 'flechettes.png',
    'Flying Knee+1': 'flying_knee.png',
    'Footwork+1': 'footwork.png',
    'Glass Knife+1': 'glass_knife.png',
    'Grand Finale+1': 'grand_finale.png',
    'Heel Hook+1': 'heel_hook.png',
    'Infinite Blades+1': 'infinite_blades.png',
    'Leg Sweep+1': 'leg_sweep.png',
    'Malaise+1': 'malaise.png',
    'Masterful Stab+1': 'masterful_stab.png',
    'Neutralize+1': 'neutralize.png',
    'Nightmare+1': 'nightmare.png',
    'Noxious Fumes+1': 'noxious_fumes.png',
    'Outmaneuver+1': 'outmaneuver.png',
    'Phantasmal Killer+1': 'phantasmal_killer.png',
    'Piercing Wail+1': 'piercing_wail.png',
    'Poisoned Stab+1': 'poisoned_stab.png',
    'Predator+1': 'predator.png',
    'Prepared+1': 'prepared.png',
    'Quick Slash+1': 'quick_slash.png',
    'Reflex+1': 'reflex.png',
    'Riddle With Holes+1': 'riddle_with_holes.png',
    'Setup+1': 'setup.png',
    'Skewer+1': 'skewer.png',
    'Slice+1': 'slice.png',
    'Sneaky Strike+1': 'sneaky_strike.png',
    'Storm of Steel+1': 'storm_of_steel.png',
    'Sucker Punch+1': 'sucker_punch.png',
    'Survivor+1': 'survivor.png',
    'Tactician+1': 'tactician.png',
    'Terror+1': 'terror.png',
    'Tools of the Trade+1': 'tools_of_the_trade.png',
    'Unload+1': 'unload.png',
    'Well Laid Plans+1': 'well_laid_plans.png',
    'Wraith Form+1': 'wraith_form.png',
  },
  red: {
    'Anger': 'anger.png',
    'Armaments': 'armaments.png',
    'Barricade': 'barricade.png',
    'Bash': 'bash.png',
    'Battle Trance': 'battle_trance.png',
    'Berserk': 'berserk.png',
    'Blood for Blood': 'blood_for_blood.png',
    'Bloodletting': 'bloodletting.png',
    'Bludgeon': 'bludgeon.png',
    'Body Slam': 'body_slam.png',
    'Brutality': 'brutality.png',
    'Burning Pact': 'burning_pact.png',
    'Carnage': 'carnage.png',
    'Clash': 'clash.png',
    'Cleave': 'cleave.png',
    'Clothesline': 'clothesline.png',
    'Combust': 'combust.png',
    'Corruption': 'corruption.png',
    'Dark Embrace': 'dark_embrace.png',
    'Defend_R': 'defend.png',
    'Demon Form': 'demon_form.png',
    'Disarm': 'disarm.png',
    'Double Tap': 'double_tap.png',
    'Dropkick': 'dropkick.png',
    'Dual Wield': 'dual_wield.png',
    'Entrench': 'entrench.png',
    'Evolve': 'evolve.png',
    'Exhume': 'exhume.png',
    'Feed': 'feed.png',
    'Feel No Pain': 'feel_no_pain.png',
    'Fiend Fire': 'fiend_fire.png',
    'Fire Breathing': 'fire_breathing.png',
    'Flame Barrier': 'flame_barrier.png',
    'Flex': 'flex.png',
    'Ghostly Armor': 'ghostly_armor.png',
    'Havoc': 'havoc.png',
    'Headbutt': 'headbutt.png',
    'Heavy Blade': 'heavy_blade.png',
    'Hemokinesis': 'hemokinesis.png',
    'Immolate': 'immolate.png',
    'Impervious': 'impervious.png',
    'Infernal Blade': 'infernal_blade.png',
    'Inflame': 'inflame.png',
    'Intimidate': 'intimidate.png',
    'Iron Wave': 'iron_wave.png',
    'Juggernaut': 'juggernaut.png',
    'Limit Break': 'limit_break.png',
    'Metallicize': 'metallicize.png',
    'Offering': 'offering.png',
    'Perfected Strike': 'perfected_strike.png',
    'Pommel Strike': 'pommel_strike.png',
    'Power Through': 'power_through.png',
    'Pummel': 'pummel.png',
    'Rage': 'rage.png',
    'Rampage': 'rampage.png',
    'Reaper': 'reaper.png',
    'Reckless Charge': 'reckless_charge.png',
    'Rupture': 'rupture.png',
    'Searing Blow': 'searing_blow.png',
    'Second Wind': 'second_wind.png',
    'Seeing Red': 'seeing_red.png',
    'Sentinel': 'sentinel.png',
    'Sever Soul': 'sever_soul.png',
    'Shockwave': 'shockwave.png',
    'Shrug It Off': 'shrug_it_off.png',
    'Spot Weakness': 'spot_weakness.png',
    'Strike_R': 'strike.png',
    'Sword Boomerang': 'sword_boomerang.png',
    'Thunder Clap': 'thunderclap.png',
    'True Grit': 'true_grit.png',
    'Twin Strike': 'twin_strike.png',
    'Uppercut': 'uppercut.png',
    'Warcry': 'warcry.png',
    'Whirlwind': 'whirlwind.png',
    'Wild Strike': 'wild_strike.png',
    
    // UPGRADED BELOW
    'Anger+1': 'anger.png',
    'Armaments+1': 'armaments.png',
    'Barricade+1': 'barricade.png',
    'Bash+1': 'bash.png',
    'Battle Trance+1': 'battle_trance.png',
    'Berserk+1': 'berserk.png',
    'Blood for Blood+1': 'blood_for_blood.png',
    'Bloodletting+1': 'bloodletting.png',
    'Bludgeon+1': 'bludgeon.png',
    'Body Slam+1': 'body_slam.png',
    'Brutality+1': 'brutality.png',
    'Burning Pact+1': 'burning_pact.png',
    'Carnage+1': 'carnage.png',
    'Clash+1': 'clash.png',
    'Cleave+1': 'cleave.png',
    'Clothesline+1': 'clothesline.png',
    'Combust+1': 'combust.png',
    'Corruption+1': 'corruption.png',
    'Dark Embrace+1': 'dark_embrace.png',
    'Defend_R+1': 'defend.png',
    'Demon Form+1': 'demon_form.png',
    'Disarm+1': 'disarm.png',
    'Double Tap+1': 'double_tap.png',
    'Dropkick+1': 'dropkick.png',
    'Dual Wield+1': 'dual_wield.png',
    'Entrench+1': 'entrench.png',
    'Evolve+1': 'evolve.png',
    'Exhume+1': 'exhume.png',
    'Feed+1': 'feed.png',
    'Feel No Pain+1': 'feel_no_pain.png',
    'Fiend Fire+1': 'fiend_fire.png',
    'Fire Breathing+1': 'fire_breathing.png',
    'Flame Barrier+1': 'flame_barrier.png',
    'Flex+1': 'flex.png',
    'Ghostly Armor+1': 'ghostly_armor.png',
    'Havoc+1': 'havoc.png',
    'Headbutt+1': 'headbutt.png',
    'Heavy Blade+1': 'heavy_blade.png',
    'Hemokinesis+1': 'hemokinesis.png',
    'Immolate+1': 'immolate.png',
    'Impervious+1': 'impervious.png',
    'Infernal Blade+1': 'infernal_blade.png',
    'Inflame+1': 'inflame.png',
    'Intimidate+1': 'intimidate.png',
    'Iron Wave+1': 'iron_wave.png',
    'Juggernaut+1': 'juggernaut.png',
    'Limit Break+1': 'limit_break.png',
    'Metallicize+1': 'metallicize.png',
    'Offering+1': 'offering.png',
    'Perfected Strike+1': 'perfected_strike.png',
    'Pommel Strike+1': 'pommel_strike.png',
    'Power Through+1': 'power_through.png',
    'Pummel+1': 'pummel.png',
    'Rage+1': 'rage.png',
    'Rampage+1': 'rampage.png',
    'Reaper+1': 'reaper.png',
    'Reckless Charge+1': 'reckless_charge.png',
    'Rupture+1': 'rupture.png',
    'Searing Blow+1': 'searing_blow.png',
    'Second Wind+1': 'second_wind.png',
    'Seeing Red+1': 'seeing_red.png',
    'Sentinel+1': 'sentinel.png',
    'Sever Soul+1': 'sever_soul.png',
    'Shockwave+1': 'shockwave.png',
    'Shrug It Off+1': 'shrug_it_off.png',
    'Spot Weakness+1': 'spot_weakness.png',
    'Strike_R+1': 'strike.png',
    'Sword Boomerang+1': 'sword_boomerang.png',
    'Thunder Clap+1': 'thunderclap.png',
    'True Grit+1': 'true_grit.png',
    'Twin Strike+1': 'twin_strike.png',
    'Uppercut+1': 'uppercut.png',
    'Warcry+1': 'warcry.png',
    'Whirlwind+1': 'whirlwind.png',
    'Wild Strike+1': 'wild_strike.png',
  },
  purple: {
    'Alpha': 'alpha.png',
    'Battle Hymn': 'battle_hymn.png',
    'Blasphemy': 'blasphemy.png',
    'Bowling Bash': 'bowling_bash.png',
    'Brilliance': 'brilliance.png',
    'Calm': 'calm.png',
    'Carve Reality': 'carve_reality.png',
    'Collect': 'collect.png',
    'Conclude': 'conclude.png',
    'Conjure Blade': 'conjure_blade.png',
    'Consecrate': 'consecrate.png',
    'Crescendo': 'crescendo.png',
    'Crush Joints': 'crush_joints.png',
    'Cut Through Fate': 'cut_through_fate.png',
    'Deceive Reality': 'deceive_reality.png',
    'Defend_P': 'defend.png',
    'Deus Ex Machina': 'deus_ex_machina.png',
    'Deva Form': 'deva_form.png',
    'Devotion': 'devotion.png',
    'Empty Body': 'empty_body.png',
    'Empty Fist': 'empty_fist.png',
    'Empty Mind': 'empty_mind.png',
    'Eruption': 'eruption.png',
    'Establishment': 'establishment.png',
    'Evaluate': 'evaluate.png',
    'Fasting': 'fasting.png',
    'Fear No Evil': 'fear_no_evil.png',
    'Flurry of Blows': 'flurry_of_blows.png',
    'Follow Up': 'follow_up.png',
    'Foreign Influence': 'foreign_influence.png',
    'Foresight': 'foresight.png',
    'Halt': 'halt.png',
    'Indignation': 'indignation.png',
    'Inner Peace': 'inner_peace.png',
    'Judgement': 'judgement.png',
    'Just Lucky': 'just_lucky.png',
    'Lesson Learned': 'lesson_learned.png',
    'Like Water': 'like_water.png',
    'Master Reality': 'master_reality.png',
    'Meditate': 'meditate.png',
    'Mental Fortress': 'mental_fortress.png',
    'Nirvana': 'nirvana.png',
    'Omniscience': 'omniscience.png',
    'Perseverance': 'perseverance.png',
    'Pray': 'pray.png',
    'Pressure Points': 'pressure_points.png',
    'Prostrate': 'prostrate.png',
    'Protect': 'protect.png',
    'Ragnarok': 'ragnarok.png',
    'Reach Heaven': 'reach_heaven.png',
    'Rushdown': 'rushdown.png',
    'Sanctity': 'sanctity.png',
    'Sands of Time': 'sands_of_time.png',
    'Sash Whip': 'sash_whip.png',
    'Scrawl': 'scrawl.png',
    'Signature Move': 'signature_move.png',
    'Simmering Fury': 'simmering_fury.png',
    'Spirit Shield': 'spirit_shield.png',
    'Strike_P': 'strike.png',
    'Study': 'study.png',
    'Swivel': 'swivel.png',
    'Talk to the Hand': 'talk_to_the_hand.png',
    'Tantrum': 'tantrum.png',
    'Third Eye': 'third_eye.png',
    'Tranquility': 'tranquility.png',
    'Unraveling': 'unraveling.png',
    'Vault': 'vault.png',
    'Vigilance': 'vigilance.png',
    'Wallop': 'wallop.png',
    'Wave of the Hand': 'wave_of_the_hand.png',
    'Weave': 'weave.png',
    'Wheel Kick': 'wheel_kick.png',
    'Windmill Strike': 'windmill_strike.png',
    'Wish': 'wish.png',
    'Worship': 'worship.png',
    'Wreath of Flame': 'wreath_of_flame.png',

    // UPGRADED BELOW
    'Alpha+1': 'alpha.png',
    'Battle Hymn+1': 'battle_hymn.png',
    'Blasphemy+1': 'blasphemy.png',
    'Bowling Bash+1': 'bowling_bash.png',
    'Brilliance+1': 'brilliance.png',
    'Calm+1': 'calm.png',
    'Carve Reality+1': 'carve_reality.png',
    'Collect+1': 'collect.png',
    'Conclude+1': 'conclude.png',
    'Conjure Blade+1': 'conjure_blade.png',
    'Consecrate+1': 'consecrate.png',
    'Crescendo+1': 'crescendo.png',
    'Crush Joints+1': 'crush_joints.png',
    'Cut Through Fate+1': 'cut_through_fate.png',
    'Deceive Reality+1': 'deceive_reality.png',
    'Defend_P+1': 'defend.png',
    'Deus Ex Machina+1': 'deus_ex_machina.png',
    'Deva Form+1': 'deva_form.png',
    'Devotion+1': 'devotion.png',
    'Empty Body+1': 'empty_body.png',
    'Empty Fist+1': 'empty_fist.png',
    'Empty Mind+1': 'empty_mind.png',
    'Eruption+1': 'eruption.png',
    'Establishment+1': 'establishment.png',
    'Evaluate+1': 'evaluate.png',
    'Fasting+1': 'fasting.png',
    'Fear No Evil+1': 'fear_no_evil.png',
    'Flurry of Blows+1': 'flurry_of_blows.png',
    'Follow Up+1': 'follow_up.png',
    'Foreign Influence+1': 'foreign_influence.png',
    'Foresight+1': 'foresight.png',
    'Halt+1': 'halt.png',
    'Indignation+1': 'indignation.png',
    'Inner Peace+1': 'inner_peace.png',
    'Judgement+1': 'judgement.png',
    'Just Lucky+1': 'just_lucky.png',
    'Lesson Learned+1': 'lesson_learned.png',
    'Like Water+1': 'like_water.png',
    'Master Reality+1': 'master_reality.png',
    'Meditate+1': 'meditate.png',
    'Mental Fortress+1': 'mental_fortress.png',
    'Nirvana+1': 'nirvana.png',
    'Omniscience+1': 'omniscience.png',
    'Perseverance+1': 'perseverance.png',
    'Pray+1': 'pray.png',
    'Pressure Points+1': 'pressure_points.png',
    'Prostrate+1': 'prostrate.png',
    'Protect+1': 'protect.png',
    'Ragnarok+1': 'ragnarok.png',
    'Reach Heaven+1': 'reach_heaven.png',
    'Rushdown+1': 'rushdown.png',
    'Sanctity+1': 'sanctity.png',
    'Sands of Time+1': 'sands_of_time.png',
    'Sash Whip+1': 'sash_whip.png',
    'Scrawl+1': 'scrawl.png',
    'Signature Move+1': 'signature_move.png',
    'Simmering Fury+1': 'simmering_fury.png',
    'Spirit Shield+1': 'spirit_shield.png',
    'Strike_P+1': 'strike.png',
    'Study+1': 'study.png',
    'Swivel+1': 'swivel.png',
    'Talk to the Hand+1': 'talk_to_the_hand.png',
    'Tantrum+1': 'tantrum.png',
    'Third Eye+1': 'third_eye.png',
    'Tranquility+1': 'tranquility.png',
    'Unraveling+1': 'unraveling.png',
    'Vault+1': 'vault.png',
    'Vigilance+1': 'vigilance.png',
    'Wallop+1': 'wallop.png',
    'Wave of the Hand+1': 'wave_of_the_hand.png',
    'Weave+1': 'weave.png',
    'Wheel Kick+1': 'wheel_kick.png',
    'Windmill Strike+1': 'windmill_strike.png',
    'Wish+1': 'wish.png',
    'Worship+1': 'worship.png',
    'Wreath of Flame+1': 'wreath_of_flame.png',
  },

  colorless: {
    'Apotheosis': 'apotheosis.png',
    'Apparition': 'apparition.png',
    'Bandage Up': 'bandage_up.png',
    'Become Almigthy': 'become_almighty.png',
    'Beta': 'beta.png',
    'Bite': 'bite.png',
    'Blind': 'blind.png',
    'Calm': 'calm.png',
    'Chrysalis': 'chrysalis.png',
    'Dark Shackles': 'dark_shackles.png',
    'Deep Breath': 'deep_breath.png',
    'Discovery': 'discovery.png',
    'Dramatic Entrance': 'dramatic_entrance.png',
    'Enlightenment': 'enlightenment.png',
    'Expunger': 'expunger.png',
    'Fame and Fortune': 'fame_and_fortune.png',
    'Finesse': 'finesse.png',
    'Flash of Steel': 'flash_of_steel.png',
    'Forethought': 'forethought.png',
    'Good Instincts': 'good_instincts.png',
    'Hand of Greed': 'hand_of_greed.png',
    'Impatience': 'impatience.png',
    'Insight': 'insight.png',
    'Jack of All Trades': 'jack_of_all_trades.png',
    'JAX': 'jax.png',
    'Live Forever': 'live_forever.png',
    'Madness': 'madness.png',
    'Magnetism': 'magnetism.png',
    'Master of Strategy': 'master_of_strategy.png',
    'Mayhem': 'mayhem.png',
    'Metamorphosis': 'metamorphosis.png',
    'Mind Blast': 'mind_blast.png',
    'Miracle': 'miracle.png',
    'Omega': 'omega.png',
    'Panacea': 'panacea.png',
    'Panic Button': 'panic_button.png',
    'Purity': 'purity.png',
    'Ritual Dagger': 'ritual_dagger.png',
    'Sadistic Nature': 'sadistic_nature.png',
    'Safety': 'safety.png',
    'Secret Technique': 'secret_technique.png',
    'Secret Weapon': 'secret_weapon.png',
    'Shiv': 'shiv.png',
    'Smite': 'smite.png',
    'Swift Strike': 'swift_strike.png',
    'The Bomb': 'the_bomb.png',
    'Thinking Ahead': 'thinking_ahead.png',
    'Through Violence': 'through_violence.png',
    'Transmutation': 'transmutation.png',
    'Trip': 'trip.png',
    'Violence': 'violence.png',
    'Wrath': 'wrath.png',

    // UPGRADED BELOW
    'Apotheosis+1': 'apotheosis.png',
    'Apparition+1': 'apparition.png',
    'Bandage Up+1': 'bandage_up.png',
    'Become Almigthy+1': 'become_almighty.png',
    'Beta+1': 'beta.png',
    'Bite+1': 'bite.png',
    'Blind+1': 'blind.png',
    'Calm+1': 'calm.png',
    'Chrysalis+1': 'chrysalis.png',
    'Dark Shackles+1': 'dark_shackles.png',
    'Deep Breath+1': 'deep_breath.png',
    'Discovery+1': 'discovery.png',
    'Dramatic Entrance+1': 'dramatic_entrance.png',
    'Enlightenment+1': 'enlightenment.png',
    'Expunger+1': 'expunger.png',
    'Fame and Fortune+1': 'fame_and_fortune.png',
    'Finesse+1': 'finesse.png',
    'Flash of Steel+1': 'flash_of_steel.png',
    'Forethought+1': 'forethought.png',
    'Good Instincts+1': 'good_instincts.png',
    'Hand of Greed+1': 'hand_of_greed.png',
    'Impatience+1': 'impatience.png',
    'Insight+1': 'insight.png',
    'Jack of All Trades+1': 'jack_of_all_trades.png',
    'JAX+1': 'jax.png',
    'Live Forever+1': 'live_forever.png',
    'Madness+1': 'madness.png',
    'Magnetism+1': 'magnetism.png',
    'Master of Strategy+1': 'master_of_strategy.png',
    'Mayhem+1': 'mayhem.png',
    'Metamorphosis+1': 'metamorphosis.png',
    'Mind Blast+1': 'mind_blast.png',
    'Miracle+1': 'miracle.png',
    'Omega+1': 'omega.png',
    'Panacea+1': 'panacea.png',
    'Panic Button+1': 'panic_button.png',
    'Purity+1': 'purity.png',
    'Ritual Dagger+1': 'ritual_dagger.png',
    'Sadistic Nature+1': 'sadistic_nature.png',
    'Safety+1': 'safety.png',
    'Secret Technique+1': 'secret_technique.png',
    'Secret Weapon+1': 'secret_weapon.png',
    'Shiv+1': 'shiv.png',
    'Smite+1': 'smite.png',
    'Swift Strike+1': 'swift_strike.png',
    'The Bomb+1': 'the_bomb.png',
    'Thinking Ahead+1': 'thinking_ahead.png',
    'Through Violence+1': 'through_violence.png',
    'Transmutation+1': 'transmutation.png',
    'Trip+1': 'trip.png',
    'Violence+1': 'violence.png',
    'Wrath+1': 'wrath.png',
  },
  status: {
    'Burn': 'burn.png',
    'Dazed': 'dazed.png',
    'Slimed': 'slimed.png',
    'Void': 'void.png',
    'Wound': 'wound.png',
  },
  curses: {
    'AscendersBane': 'ascenders_bane.png',
    'Clumsy': 'clumsy.png',
    'Curse Of The Bell': 'curse_of_the_bell.png',
    'Decay': 'decay.png',
    'Doubt': 'doubt.png',
    'Injury': 'injury.png',
    'Necronomicurse': 'necronomicurse.png',
    'Normality': 'normality.png',
    'Pain': 'pain.png',
    'Parasite': 'parasite.png',
    'Pride': 'pride.png',
    'Regret': 'regret.png',
    'Shame': 'shame.png',
    'Writhe': 'writhe.png',
  }
};


export default cards;