const cards = {
  blue: {
      'Strike_B': 'strike.png',
      'All For One': 'all_for_one.png',
      'Ball Lightning': 'ball_lightning.png',
      'Barrage': 'barrage.png',
      'Beam Cell': 'beam_cell.png',
      'Blizzard': 'blizzard.png',
      'Claw': 'claw.png',
      'Cold Snap': 'cold_snap.png',
      'Compile Driver': 'compile_driver.png',
      'Core Surge': 'core_surge.png',
      'Doom and Gloom': 'doom_and_gloom.png',
      'FTL': 'ftl.png',
      'Go For The Eyes': 'go_for_the_eyes.png',
      'Hyper Beam': 'hyper_beam.png',
      'Lock On': 'lock_on.png',
      'Melter': 'melter.png',
      'Meteor Strike': 'meteor_strike.png',
      'Rebound': 'rebound.png',
      'Rip And Tear': 'rip_and_tear.png',
      'Scrape': 'scrape.png',
      'Steamline': 'steamline.png',
      'Sunder': 'sunder.png',
      'Sweeping Beam': 'sweeping_beam.png',
      'Thunder Strike': 'thunder_strike.png',
      'Biased Cognition': 'biased_cognition.png',
      'Buffer': 'buffer.png',
      'Capacitor': 'capacitor.png',
      'Creative AI': 'creative_ai.png',
      'Defragment': 'defragment.png',
      'Echo Form': 'echo_form.png',
      'Electrodynamics': 'electrodynamics.png',
      'Heatsinks': 'heatsinks.png',
      'Hello World': 'hello_world.png',
      'Lightning Mastery': 'lightning_mastery.png',
      'Loop': 'loop.png',
      'Machine Learning': 'machine_learning.png',
      'Storm': 'storm.png',
      'Static Discharge': 'static_discharge.png',
      'Self Repair': 'self_repair.png',
      'Aggregate': 'aggregate.png',
      'Amplify': 'amplify.png',
      'Auto Shields': 'auto_shields.png',
      'Boot Sequence': 'boot_sequence.png',
      'Chaos': 'chaos.png',
      'Charge Battery': 'charge_battery.png',
      'Chill': 'chill.png',
      'Consume': 'consume.png',
      'Coolheaded': 'coolheaded.png',
      'Darkness': 'darkness.png',
      'Defend_B': 'defend.png',
      'Double Energy': 'double_energy.png',
      'Dualcast': 'dualcast.png',
      'Equilibrium': 'equilibrium.png',
      'Fission': 'fission.png',
      'Force Field': 'force_field.png',
      'Fusion': 'fusion.png',
      'Genetic Algorithm': 'genetic_algorithm.png',
      'Glacier': 'glacier.png',
      'Hologram': 'hologram.png',
      'Leap': 'leap.png',
      'Multicast': 'multicast.png',
      'Overclock': 'overclock.png',
      'Rainbow': 'rainbow.png',
      'Reboot': 'reboot.png',
      'Recursion': 'recursion.png',
      'Recycle': 'recycle.png',
      'Reinforced Body': 'reinforced_body.png',
      'Reprogram': 'reprogram.png',
      'Seek': 'seek.png',
      'Skim': 'skim.png',
      'Stack': 'stack.png',
      'Steam Barrier': 'steam_barrier.png',
      'Tempest': 'tempest.png',
      'Turbo': 'turbo.png',
      'White Noise': 'white_noise.png',
      'Zap': 'zap.png',
      
      // UPGRADED BELOW
      'Strike_B+1': 'strike.png',
      'All For One+1': 'all_for_one.png',
      'Ball Lightning+1': 'ball_lightning.png',
      'Barrage+1': 'barrage.png',
      'Beam Cell+1': 'beam_cell.png',
      'Blizzard+1': 'blizzard.png',
      'Claw+1': 'claw.png',
      'Cold Snap+1': 'cold_snap.png',
      'Compile Driver+1': 'compile_driver.png',
      'Core Surge+1': 'core_surge.png',
      'Doom and Gloom+1': 'doom_and_gloom.png',
      'FTL+1': 'ftl.png',
      'Go For The Eyes+1': 'go_for_the_eyes.png',
      'Hyper Beam+1': 'hyper_beam.png',
      'Lock On+1': 'lock_on.png',
      'Melter+1': 'melter.png',
      'Meteor Strike+1': 'meteor_strike.png',
      'Rebound+1': 'rebound.png',
      'Rip And Tear+1': 'rip_and_tear.png',
      'Scrape+1': 'scrape.png',
      'Steamline+1': 'steamline.png',
      'Sunder+1': 'sunder.png',
      'Sweeping Beam+1': 'sweeping_beam.png',
      'Thunder Strike+1': 'thunder_strike.png',
      'Biased Cognition+1': 'biased_cognition.png',
      'Buffer+1': 'buffer.png',
      'Capacitor+1': 'capacitor.png',
      'Creative AI+1': 'creative_ai.png',
      'Defragment+1': 'defragment.png',
      'Echo Form+1': 'echo_form.png',
      'Electrodynamics+1': 'electrodynamics.png',
      'Heatsinks+1': 'heatsinks.png',
      'Hello World+1': 'hello_world.png',
      'Lightning Mastery+1': 'lightning_mastery.png',
      'Loop+1': 'loop.png',
      'Machine Learning+1': 'machine_learning.png',
      'Storm+1': 'storm.png',
      'Static Discharge+1': 'static_discharge.png',
      'Self Repair+1': 'self_repair.png',
      'Aggregate+1': 'aggregate.png',
      'Amplify+1': 'amplify.png',
      'Auto Shields+1': 'auto_shields.png',
      'Boot Sequence+1': 'boot_sequence.png',
      'Chaos+1': 'chaos.png',
      'Charge Battery+1': 'charge_battery.png',
      'Chill+1': 'chill.png',
      'Consume+1': 'consume.png',
      'Coolheaded+1': 'coolheaded.png',
      'Darkness+1': 'darkness.png',
      'Defend_B+1': 'defend.png',
      'Double Energy+1': 'double_energy.png',
      'Dualcast+1': 'dualcast.png',
      'Equilibrium+1': 'equilibrium.png',
      'Fission+1': 'fission.png',
      'Force Field+1': 'force_field.png',
      'Fusion+1': 'fusion.png',
      'Genetic Algorithm+1': 'genetic_algorithm.png',
      'Glacier+1': 'glacier.png',
      'Hologram+1': 'hologram.png',
      'Leap+1': 'leap.png',
      'Multicast+1': 'multicast.png',
      'Overclock+1': 'overclock.png',
      'Rainbow+1': 'rainbow.png',
      'Reboot+1': 'reboot.png',
      'Recursion+1': 'recursion.png',
      'Recycle+1': 'recycle.png',
      'Reinforced Body+1': 'reinforced_body.png',
      'Reprogram+1': 'reprogram.png',
      'Seek+1': 'seek.png',
      'Skim+1': 'skim.png',
      'Stack+1': 'stack.png',
      'Steam Barrier+1': 'steam_barrier.png',
      'Tempest+1': 'tempest.png',
      'Turbo+1': 'turbo.png',
      'White Noise+1': 'white_noise.png',
      'Zap+1': 'zap.png',
  },
  green: {
    'Strike_G': 'strike.png',
    'A Thousand Cuts': 'a_thousand_cuts.png',
    'Accuracy': 'accuracy.png',
    'Acrobatics': 'acrobatics.png',
    'Adrenaline': 'adrenaline.png',
    'After Image': 'after_image.png',
    'Alchemize': 'alchemize.png',
    'All Out Attack': 'all_out_attack.png',
    'Backflip': 'backflip.png',
    'Backstab': 'backstab.png',
    'Bane': 'bane.png',
    'Blade Dance': 'blade_dance.png',
    'Blur': 'blur.png',
    'Bouncing Flask': 'bouncing_flask.png',
    'Bullet Time': 'bullet_time.png',
    'Burst': 'burst.png',
    'Calculated Gamble': 'calculated_gamble.png',
    'Caltrops': 'caltrops.png',
    'Catalyst': 'catalyst.png',
    'Choke': 'choke.png',
    'Cloak and Dagger': 'cloak_and_dagger.png',
    'Concentrate': 'concentrate.png',
    'Corpse Explosion': 'corpse_explosion.png',
    'Crippling Poison': 'crippling_poison.png',
    'Dagger Spray': 'dagger_spray.png',
    'Dagger Throw': 'dagger_throw.png',
    'Dash': 'dash.png',
    'Deadly Poison': 'deadly_poison.png',
    'Defend_G': 'defend.png',
    'Deflect': 'deflect.png',
    'Die Die Die': 'die_die_die.png',
    'Distraction': 'distraction.png',
    'Dodge and Roll': 'dodge_and_roll.png',
    'Doppelganger': 'doppelganger.png',
    'Endless Agony': 'endless_agony.png',
    'Envenom': 'envenom.png',
    'Escape Plan': 'escape_plan.png',
    'Eviscerate': 'eviscerate.png',
    'Expertise': 'expertise.png',
    'Finisher': 'finisher.png',
    'Flechettes': 'flechettes.png',
    'Flying Knee': 'flying_knee.png',
    'Footwork': 'footwork.png',
    'Glass Knife': 'glass_knife.png',
    'Grand Finale': 'grand_finale.png',
    'Heel Hook': 'heel_hook.png',
    'Infinite Blades': 'infinite_blades.png',
    'Leg Sweep': 'leg_sweep.png',
    'Malaise': 'malaise.png',
    'Masterful Stab': 'masterful_stab.png',
    'Neutralize': 'neutralize.png',
    'Nightmare': 'nightmare.png',
    'Noxious Fumes': 'noxious_fumes.png',
    'Outmaneuver': 'outmaneuver.png',
    'Phantasmal Killer': 'phantasmal_killer.png',
    'Piercing Wail': 'piercing_wail.png',
    'Poisoned Stab': 'poisoned_stab.png',
    'Predator': 'predator.png',
    'Prepared': 'prepared.png',
    'Quick Slash': 'quick_slash.png',
    'Reflex': 'reflex.png',
    'Riddle With Holes': 'riddle_with_holes.png',
    'Setup': 'setup.png',
    'Skewer': 'skewer.png',
    'Slice': 'slice.png',
    'Sneaky Strike': 'sneaky_strike.png',
    'Storm of Steel': 'storm_of_steel.png',
    'Sucker Punch': 'sucker_punch.png',
    'Survivor': 'survivor.png',
    'Tactician': 'tactician.png',
    'Terror': 'terror.png',
    'Tools of the Trade': 'tools_of_the_trade.png',
    'Unload': 'unload.png',
    'Well Laid Plans': 'well_laid_plans.png',
    'Wraith Form': 'wraith_form.png',

    // UPGRADED BELOW
    'Strike_G+1': 'strike.png',
    'A Thousand Cuts+1': 'a_thousand_cuts.png',
    'Accuracy+1': 'accuracy.png',
    'Acrobatics+1': 'acrobatics.png',
    'Adrenaline+1': 'adrenaline.png',
    'After Image+1': 'after_image.png',
    'Alchemize+1': 'alchemize.png',
    'All Out Attack+1': 'all_out_attack.png',
    'Backflip+1': 'backflip.png',
    'Backstab+1': 'backstab.png',
    'Bane+1': 'bane.png',
    'Blade Dance+1': 'blade_dance.png',
    'Blur+1': 'blur.png',
    'Bouncing Flask+1': 'bouncing_flask.png',
    'Bullet Time+1': 'bullet_time.png',
    'Burst+1': 'burst.png',
    'Calculated Gamble+1': 'calculated_gamble.png',
    'Caltrops+1': 'caltrops.png',
    'Catalyst+1': 'catalyst.png',
    'Choke+1': 'choke.png',
    'Cloak and Dagger+1': 'cloak_and_dagger.png',
    'Concentrate+1': 'concentrate.png',
    'Corpse Explosion+1': 'corpse_explosion.png',
    'Crippling Poison+1': 'crippling_poison.png',
    'Dagger Spray+1': 'dagger_spray.png',
    'Dagger Throw+1': 'dagger_throw.png',
    'Dash+1': 'dash.png',
    'Deadly Poison+1': 'deadly_poison.png',
    'Defend_G+1': 'defend.png',
    'Deflect+1': 'deflect.png',
    'Die Die Die+1': 'die_die_die.png',
    'Distraction+1': 'distraction.png',
    'Dodge and Roll+1': 'dodge_and_roll.png',
    'Doppelganger+1': 'doppelganger.png',
    'Endless Agony+1': 'endless_agony.png',
    'Envenom+1': 'envenom.png',
    'Escape Plan+1': 'escape_plan.png',
    'Eviscerate+1': 'eviscerate.png',
    'Expertise+1': 'expertise.png',
    'Finisher+1': 'finisher.png',
    'Flechettes+1': 'flechettes.png',
    'Flying Knee+1': 'flying_knee.png',
    'Footwork+1': 'footwork.png',
    'Glass Knife+1': 'glass_knife.png',
    'Grand Finale+1': 'grand_finale.png',
    'Heel Hook+1': 'heel_hook.png',
    'Infinite Blades+1': 'infinite_blades.png',
    'Leg Sweep+1': 'leg_sweep.png',
    'Malaise+1': 'malaise.png',
    'Masterful Stab+1': 'masterful_stab.png',
    'Neutralize+1': 'neutralize.png',
    'Nightmare+1': 'nightmare.png',
    'Noxious Fumes+1': 'noxious_fumes.png',
    'Outmaneuver+1': 'outmaneuver.png',
    'Phantasmal Killer+1': 'phantasmal_killer.png',
    'Piercing Wail+1': 'piercing_wail.png',
    'Poisoned Stab+1': 'poisoned_stab.png',
    'Predator+1': 'predator.png',
    'Prepared+1': 'prepared.png',
    'Quick Slash+1': 'quick_slash.png',
    'Reflex+1': 'reflex.png',
    'Riddle With Holes+1': 'riddle_with_holes.png',
    'Setup+1': 'setup.png',
    'Skewer+1': 'skewer.png',
    'Slice+1': 'slice.png',
    'Sneaky Strike+1': 'sneaky_strike.png',
    'Storm of Steel+1': 'storm_of_steel.png',
    'Sucker Punch+1': 'sucker_punch.png',
    'Survivor+1': 'survivor.png',
    'Tactician+1': 'tactician.png',
    'Terror+1': 'terror.png',
    'Tools of the Trade+1': 'tools_of_the_trade.png',
    'Unload+1': 'unload.png',
    'Well Laid Plans+1': 'well_laid_plans.png',
    'Wraith Form+1': 'wraith_form.png',
  },

  colorless: {
    'Apotheosis': 'apotheosis.png',
    'Apparition': 'apparition.png',
    'Bandage Up': 'bandage_up.png',
    'Become Almigthy': 'become_almighty.png',
    'Beta': 'beta.png',
    'Bite': 'bite.png',
    'Blind': 'blind.png',
    'Calm': 'calm.png',
    'Chrysalis': 'chrysalis.png',
    'Dark Shackles': 'dark_shackles.png',
    'Deep Breath': 'deep_breath.png',
    'Discovery': 'discovery.png',
    'Dramatic Entrance': 'dramatic_entrance.png',
    'Enlightenment': 'enlightenment.png',
    'Expunger': 'expunger.png',
    'Fame and Fortune': 'fame_and_fortune.png',
    'Finesse': 'finesse.png',
    'Flash of Steel': 'flash_of_steel.png',
    'Forethought': 'forethought.png',
    'Good Instincts': 'good_instincts.png',
    'Hand of Greed': 'hand_of_greed.png',
    'Impatience': 'impatience.png',
    'Insight': 'insight.png',
    'Jack of All Trades': 'jack_of_all_trades.png',
    'JAX': 'jax.png',
    'Live Forever': 'live_forever.png',
    'Madness': 'madness.png',
    'Magnetism': 'magnetism.png',
    'Master of Strategy': 'master_of_strategy.png',
    'Mayhem': 'mayhem.png',
    'Metamorphosis': 'metamorphosis.png',
    'Mind Blast': 'mind_blast.png',
    'Miracle': 'miracle.png',
    'Omega': 'omega.png',
    'Panacea': 'panacea.png',
    'Panic Button': 'panic_button.png',
    'Purity': 'purity.png',
    'Ritual Dagger': 'ritual_dagger.png',
    'Sadistic Nature': 'sadistic_nature.png',
    'Safety': 'safety.png',
    'Secret Technique': 'secret_technique.png',
    'Secret Weapon': 'secret_weapon.png',
    'Shiv': 'shiv.png',
    'Smite': 'smite.png',
    'Swift Strike': 'swift_strike.png',
    'The Bomb': 'the_bomb.png',
    'Thinking Ahead': 'thinking_ahead.png',
    'Through Violence': 'through_violence.png',
    'Transmutation': 'transmutation.png',
    'Trip': 'trip.png',
    'Violence': 'violence.png',
    'Wrath': 'wrath.png',
  },
  status: {
    'Burn': 'burn.png',
    'Dazed': 'dazed.png',
    'Slimed': 'slimed.png',
    'Void': 'void.png',
    'Wound': 'wound.png',
  },
  curses: {
    'AscendersBane': 'ascenders_bane.png',
    'Clumsy': 'clumsy.png',
    'Curse Of The Bell': 'curse_of_the_bell.png',
    'Decay': 'decay.png',
    'Doubt': 'doubt.png',
    'Injury': 'injury.png',
    'Necronomicurse': 'necronomicurse.png',
    'Normality': 'normality.png',
    'Pain': 'pain.png',
    'Parasite': 'parasite.png',
    'Pride': 'pride.png',
    'Regret': 'regret.png',
    'Shame': 'shame.png',
    'Writhe': 'writhe.png',
  }
};


export default cards;