const cards = {
  blue: {
      'Strike_B': 'strike_b.png',
      'All For One': 'AllForOne.png',
      'Ball Lightning': 'BallLightning.png',
      'Barrage': 'barrage.png',
      'Beam Cell': 'BeamCell.png',
      'Blizzard': 'blizzard.png',
      'BootSequence': 'BootSequence.png',
      'Gash': 'claw.png',
      'Cold Snap': 'ColdSnap.png',
      'Compile Driver': 'CompileDriver.png',
      'Core Surge': 'CoreSurge.png',
      'Doom and Gloom': 'DoomAndGloom.png',
      'FTL': 'ftl.png',
      'Go for the Eyes': 'GoForTheEyes.png',
      'Hyperbeam': 'HyperBeam.png',
      'Lockon': 'Bullseye.png',
      'Melter': 'melter.png',
      'Meteor Strike': 'MeteorStrike.png',
      'Rebound': 'rebound.png',
      'Rip and Tear': 'RipAndTear.png',
      'Scrape': 'scrape.png',
      'Streamline': 'streamline.png',
      'Sunder': 'sunder.png',
      'Sweeping Beam': 'SweepingBeam.png',
      'Thunder Strike': 'ThunderStrike.png',
      'Biased Cognition': 'BiasedCognition.png',
      'Buffer': 'buffer.png',
      'Capacitor': 'capacitor.png',
      'Creative AI': 'CreativeAi.png',
      'Defragment': 'defragment.png',
      'Echo Form': 'EchoForm.png',
      'Electrodynamics': 'electrodynamics.png',
      'Heatsinks': 'heatsinks.png',
      'Hello World': 'HelloWorld.png',
      'Lightning Mastery': 'LightningMastery.png',
      'Loop': 'loop.png',
      'Machine Learning': 'MachineLearning.png',
      'Storm': 'storm.png',
      'Static Discharge': 'StaticDischarge.png',
      'Self Repair': 'SelfRepair.png',
      'Aggregate': 'aggregate.png',
      'Amplify': 'amplify.png',
      'Auto Shields': 'AutoShields.png',
      'Boot Sequence': 'BootSequence.png',
      'Chaos': 'chaos.png',
      'Conserve Battery': 'ChargeBattery.png',
      'Chill': 'chill.png',
      'Consume': 'consume.png',
      'Coolheaded': 'coolheaded.png',
      'Darkness': 'darkness.png',
      'Defend_B': 'defend_b.png',
      'Double Energy': 'DoubleEnergy.png',
      'Dualcast': 'dualcast.png',
      'Equilibrium': 'equilibrium.png',
      'Fission': 'fission.png',
      'Force Field': 'forcefield.png',
      'Fusion': 'fusion.png',
      'Genetic Algorithm': 'GeneticAlgorithm.png',
      'Glacier': 'glacier.png',
      'Hologram': 'hologram.png',
      'Leap': 'leap.png',
      'Multi-Cast': 'multicast.png',
      'Overclock': 'overclock.png',
      'Rainbow': 'rainbow.png',
      'Reboot': 'reboot.png',
      'Redo': 'recursion.png',
      'Recycle': 'recycle.png',
      'Reinforced Body': 'ReinforcedBody.png',
      'Reprogram': 'reprogram.png',
      'Seek': 'seek.png',
      'Skim': 'skim.png',
      'Stack': 'stack.png',
      'Steam': 'SteamBarrier.png',
      'Tempest': 'tempest.png',
      'Turbo': 'turbo.png',
      'White Noise': 'WhiteNoise.png',
      'Zap': 'zap.png',
      
      // UPGRADED BELOW
      'Strike_B+1': 'strike_b.png',
      'All For One+1': 'AllForOne.png',
      'Ball Lightning+1': 'BallLightning.png',
      'Barrage+1': 'barrage.png',
      'Beam Cell+1': 'BeamCell.png',
      'BootSequence+1': 'BootSequence.png',
      'Blizzard+1': 'blizzard.png',
      'Gash+1': 'claw.png',
      'Cold Snap+1': 'ColdSnap.png',
      'Compile Driver+1': 'CompileDriver.png',
      'Core Surge+1': 'CoreSurge.png',
      'Doom and Gloom+1': 'DoomAndGloom.png',
      'FTL+1': 'ftl.png',
      'Go for the Eyes+1': 'GoForTheEyes.png',
      'Hyperbeam+1': 'HyperBeam.png',
      'Lockon+1': 'Bullseye.png',
      'Melter+1': 'melter.png',
      'Meteor Strike+1': 'MeteorStrike.png',
      'Rebound+1': 'rebound.png',
      'Rip and Tear+1': 'RipAndTear.png',
      'Scrape+1': 'scrape.png',
      'Streamline+1': 'streamline.png',
      'Sunder+1': 'sunder.png',
      'Sweeping Beam+1': 'SweepingBeam.png',
      'Thunder Strike+1': 'ThunderStrike.png',
      'Biased Cognition+1': 'BiasedCognition.png',
      'Buffer+1': 'buffer.png',
      'Capacitor+1': 'capacitor.png',
      'Creative AI+1': 'CreativeAi.png',
      'Defragment+1': 'defragment.png',
      'Echo Form+1': 'EchoForm.png',
      'Electrodynamics+1': 'electrodynamics.png',
      'Heatsinks+1': 'heatsinks.png',
      'Hello World+1': 'HelloWorld.png',
      'Lightning Mastery+1': 'LightningMastery.png',
      'Loop+1': 'loop.png',
      'Machine Learning+1': 'MachineLearning.png',
      'Storm+1': 'storm.png',
      'Static Discharge+1': 'StaticDischarge.png',
      'Self Repair+1': 'SelfRepair.png',
      'Aggregate+1': 'aggregate.png',
      'Amplify+1': 'amplify.png',
      'Auto Shields+1': 'AutoShields.png',
      'Boot Sequence+1': 'BootSequence.png',
      'Chaos+1': 'chaos.png',
      'Conserve Battery+1': 'ChargeBattery.png',
      'Chill+1': 'chill.png',
      'Consume+1': 'consume.png',
      'Coolheaded+1': 'coolheaded.png',
      'Darkness+1': 'darkness.png',
      'Defend_B+1': 'defend_b.png',
      'Double Energy+1': 'DoubleEnergy.png',
      'Dualcast+1': 'dualcast.png',
      'Equilibrium+1': 'equilibrium.png',
      'Fission+1': 'fission.png',
      'Force Field+1': 'forcefield.png',
      'Fusion+1': 'fusion.png',
      'Genetic Algorithm+1': 'GeneticAlgorithm.png',
      'Glacier+1': 'glacier.png',
      'Hologram+1': 'hologram.png',
      'Leap+1': 'leap.png',
      'Multi-Cast+1': 'multicast.png',
      'Overclock+1': 'overclock.png',
      'Rainbow+1': 'rainbow.png',
      'Reboot+1': 'reboot.png',
      'Redo+1': 'recursion.png',
      'Recycle+1': 'recycle.png',
      'Reinforced Body+1': 'ReinforcedBody.png',
      'Reprogram+1': 'reprogram.png',
      'Seek+1': 'seek.png',
      'Skim+1': 'skim.png',
      'Stack+1': 'stack.png',
      'Steam+1': 'SteamBarrier.png',
      'Tempest+1': 'tempest.png',
      'Turbo+1': 'turbo.png',
      'White Noise+1': 'WhiteNoise.png',
      'Zap+1': 'zap.png',
  },
  green: {
    'Strike_G': 'strike_g.png',
    'A Thousand Cuts': 'AThousandCuts.png',
    'Accuracy': 'accuracy.png',
    'Acrobatics': 'acrobatics.png',
    'Adrenaline': 'adrenaline.png',
    'After Image': 'AfterImage.png',
    'Alchemize': 'alchemize.png',
    'All Out Attack': 'AllOutAttack.png',
    'Backflip': 'backflip.png',
    'Backstab': 'backstab.png',
    'Bane': 'bane.png',
    'Blade Dance': 'BladeDance.png',
    'Blur': 'blur.png',
    'Bouncing Flask': 'BouncingFlask.png',
    'Bullet Time': 'BulletTime.png',
    'Burst': 'burst.png',
    'Calculated Gamble': 'CalculatedGamble.png',
    'Caltrops': 'caltrops.png',
    'Catalyst': 'catalyst.png',
    'Choke': 'choke.png',
    'Cloak And Dagger': 'CloakAndDagger.png',
    'Concentrate': 'concentrate.png',
    'Corpse Explosion': 'CorpseExplosion.png',
    'Crippling Poison': 'CripplingCloud.png',
    'Dagger Spray': 'DaggerSpray.png',
    'Dagger Throw': 'DaggerThrow.png',
    'Dash': 'dash.png',
    'Deadly Poison': 'DeadlyPoison.png',
    'Defend_G': 'defend_g.png',
    'Deflect': 'deflect.png',
    'Die Die Die': 'DieDieDie.png',
    'Distraction': 'distraction.png',
    'Dodge and Roll': 'DodgeAndRoll.png',
    'Doppelganger': 'doppelganger.png',
    'Endless Agony': 'EndlessAgony.png',
    'Envenom': 'envenom.png',
    'Escape Plan': 'EscapePlan.png',
    'Eviscerate': 'eviscerate.png',
    'Expertise': 'expertise.png',
    'Finisher': 'finisher.png',
    'Flechettes': 'flechettes.png',
    'Flying Knee': 'FlyingKnee.png',
    'Footwork': 'footwork.png',
    'Glass Knife': 'GlassKnife.png',
    'Grand Finale': 'GrandFinale.png',
    'Heel Hook': 'HeelHook.png',
    'Infinite Blades': 'InfiniteBlades.png',
    'Leg Sweep': 'LegSweep.png',
    'Malaise': 'malaise.png',
    'Masterful Stab': 'MasterfulStab.png',
    'Neutralize': 'neutralize.png',
    'Nightmare': 'nightmare.png',
    'Noxious Fumes': 'noxiousfumes.png',
    'Outmaneuver': 'outmaneuver.png',
    'Phantasmal Killer': 'phantasmalkiller.png',
    'PiercingWail': 'piercingwail.png',
    'Poisoned Stab': 'poisonedstab.png',
    'Predator': 'predator.png',
    'Prepared': 'prepared.png',
    'Quick Slash': 'quickslash.png',
    'Reflex': 'reflex.png',
    'Riddle With Holes': 'riddlewithholes.png',
    'Setup': 'setup.png',
    'Skewer': 'skewer.png',
    'Slice': 'slice.png',
    'Underhanded Strike': 'sneakystrike.png',
    'Storm of Steel': 'stormofsteel.png',
    'Sucker Punch': 'suckerpunch.png',
    'Survivor': 'survivor.png',
    'Tactician': 'tactician.png',
    'Terror': 'terror.png',
    'Tools of the Trade': 'toolsofthetrade.png',
    'Unload': 'unload.png',
    'Well Laid Plans': 'welllaidplans.png',
    'Wraith Form': 'wraithform.png',

    // UPGRADED BELOW
    'Strike_G+1': 'strike_g.png',
    'A Thousand Cuts+1': 'AThousandCuts.png',
    'Accuracy+1': 'accuracy.png',
    'Acrobatics+1': 'acrobatics.png',
    'Adrenaline+1': 'adrenaline.png',
    'After Image+1': 'AfterImage.png',
    'Alchemize+1': 'alchemize.png',
    'All Out Attack+1': 'AllOutAttack.png',
    'Backflip+1': 'backflip.png',
    'Backstab+1': 'backstab.png',
    'Bane+1': 'bane.png',
    'Blade Dance+1': 'BladeDance.png',
    'Blur+1': 'blur.png',
    'Bouncing Flask+1': 'BouncingFlask.png',
    'Bullet Time+1': 'BulletTime.png',
    'Burst+1': 'burst.png',
    'Calculated Gamble+1': 'CalculatedGamble.png',
    'Caltrops+1': 'caltrops.png',
    'Catalyst+1': 'catalyst.png',
    'Choke+1': 'choke.png',
    'Cloak And Dagger+1': 'CloakAndDagger.png',
    'Concentrate+1': 'concentrate.png',
    'Corpse Explosion+1': 'CorpseExplosion.png',
    'Crippling Poison+1': 'CripplingCloud.png',
    'Dagger Spray+1': 'DaggerSpray.png',
    'Dagger Throw+1': 'DaggerThrow.png',
    'Dash+1': 'dash.png',
    'Deadly Poison+1': 'DeadlyPoison.png',
    'Defend_G+1': 'defend_g.png',
    'Deflect+1': 'deflect.png',
    'Die Die Die+1': 'DieDieDie.png',
    'Distraction+1': 'distraction.png',
    'Dodge and Roll+1': 'DodgeAndRoll.png',
    'Doppelganger+1': 'doppelganger.png',
    'Endless Agony+1': 'EndlessAgony.png',
    'Envenom+1': 'envenom.png',
    'Escape Plan+1': 'EscapePlan.png',
    'Eviscerate+1': 'eviscerate.png',
    'Expertise+1': 'expertise.png',
    'Finisher+1': 'finisher.png',
    'Flechettes+1': 'flechettes.png',
    'Flying Knee+1': 'FlyingKnee.png',
    'Footwork+1': 'footwork.png',
    'Glass Knife+1': 'GlassKnife.png',
    'Grand Finale+1': 'GrandFinale.png',
    'Heel Hook+1': 'HeelHook.png',
    'Infinite Blades+1': 'InfiniteBlades.png',
    'Leg Sweep+1': 'LegSweep.png',
    'Malaise+1': 'malaise.png',
    'Masterful Stab+1': 'MasterfulStab.png',
    'Neutralize+1': 'neutralize.png',
    'Nightmare+1': 'nightmare.png',
    'Noxious Fumes+1': 'noxiousfumes.png',
    'Outmaneuver+1': 'outmaneuver.png',
    'Phantasmal Killer+1': 'phantasmalkiller.png',
    'PiercingWail+1': 'piercingwail.png',
    'Poisoned Stab+1': 'poisonedstab.png',
    'Predator+1': 'predator.png',
    'Prepared+1': 'prepared.png',
    'Quick Slash+1': 'quickslash.png',
    'Reflex+1': 'reflex.png',
    'Riddle With Holes+1': 'riddlewithholes.png',
    'Setup+1': 'setup.png',
    'Skewer+1': 'skewer.png',
    'Slice+1': 'slice.png',
    'Underhanded Strike+1': 'sneakystrike.png',
    'Storm of Steel+1': 'stormofsteel.png',
    'Sucker Punch+1': 'suckerpunch.png',
    'Survivor+1': 'survivor.png',
    'Tactician+1': 'tactician.png',
    'Terror+1': 'terror.png',
    'Tools of the Trade+1': 'toolsofthetrade.png',
    'Unload+1': 'unload.png',
    'Well Laid Plans+1': 'welllaidplans.png',
    'Wraith Form+1': 'wraithform.png',
  },
  red: {
    'Anger': 'anger.png',
    'Armaments': 'armaments.png',
    'Barricade': 'barricade.png',
    'Bash': 'bash.png',
    'Battle Trance': 'BattleTrance.png',
    'Berserk': 'berserk.png',
    'Blood for Blood': 'BloodForBlood.png',
    'Bloodletting': 'bloodletting.png',
    'Bludgeon': 'bludgeon.png',
    'Body Slam': 'BodySlam.png',
    'Brutality': 'brutality.png',
    'Burning Pact': 'BurningPact.png',
    'Carnage': 'carnage.png',
    'Clash': 'clash.png',
    'Cleave': 'cleave.png',
    'Clothesline': 'clothesline.png',
    'Combust': 'combust.png',
    'Corruption': 'corruption.png',
    'Dark Embrace': 'DarkEmbrace.png',
    'Defend_R': 'Defend_R.png',
    'Demon Form': 'DemonForm.png',
    'Disarm': 'disarm.png',
    'Double Tap': 'DoubleTap.png',
    'Dropkick': 'dropkick.png',
    'Dual Wield': 'DualWield.png',
    'Entrench': 'entrench.png',
    'Evolve': 'evolve.png',
    'Exhume': 'exhume.png',
    'Feed': 'feed.png',
    'Feel No Pain': 'FeelNoPain.png',
    'Fiend Fire': 'FiendFire.png',
    'Fire Breathing': 'FireBreathing.png',
    'Flame Barrier': 'FlameBarrier.png',
    'Flex': 'flex.png',
    'Ghostly Armor': 'GhostlyArmor.png',
    'Havoc': 'havoc.png',
    'Headbutt': 'headbutt.png',
    'Heavy Blade': 'HeavyBlade.png',
    'Hemokinesis': 'hemokinesis.png',
    'Immolate': 'immolate.png',
    'Impervious': 'impervious.png',
    'Infernal Blade': 'InfernalBlade.png',
    'Inflame': 'inflame.png',
    'Intimidate': 'intimidate.png',
    'Iron Wave': 'IronWave.png',
    'Juggernaut': 'juggernaut.png',
    'Limit Break': 'LimitBreak.png',
    'Metallicize': 'metallicize.png',
    'Offering': 'offering.png',
    'Perfected Strike': 'PerfectedStrike.png',
    'Pommel Strike': 'PommelStrike.png',
    'Power Through': 'PowerThrough.png',
    'Pummel': 'pummel.png',
    'Rage': 'rage.png',
    'Rampage': 'rampage.png',
    'Reaper': 'reaper.png',
    'Reckless Charge': 'RecklessCharge.png',
    'Rupture': 'rupture.png',
    'Searing Blow': 'SearingBlow.png',
    'Second Wind': 'SecondWind.png',
    'Seeing Red': 'SeeingRed.png',
    'Sentinel': 'sentinel.png',
    'Sever Soul': 'SeverSoul.png',
    'Shockwave': 'shockwave.png',
    'Shrug It Off': 'ShrugItOff.png',
    'Spot Weakness': 'SpotWeakness.png',
    'Strike_R': 'Strike_R.png',
    'Sword Boomerang': 'SwordBoomerang.png',
    'Thunder Clap': 'thunderclap.png',
    'True Grit': 'TrueGrit.png',
    'Twin Strike': 'TwinStrike.png',
    'Uppercut': 'uppercut.png',
    'Warcry': 'warcry.png',
    'Whirlwind': 'whirlwind.png',
    'Wild Strike': 'WildStrike.png',
    
    // UPGRADED BELOW
    'Anger+1': 'anger.png',
    'Armaments+1': 'armaments.png',
    'Barricade+1': 'barricade.png',
    'Bash+1': 'bash.png',
    'Battle Trance+1': 'BattleTrance.png',
    'Berserk+1': 'berserk.png',
    'Blood for Blood+1': 'BloodForBlood.png',
    'Bloodletting+1': 'bloodletting.png',
    'Bludgeon+1': 'bludgeon.png',
    'Body Slam+1': 'BodySlam.png',
    'Brutality+1': 'brutality.png',
    'Burning Pact+1': 'BurningPact.png',
    'Carnage+1': 'carnage.png',
    'Clash+1': 'clash.png',
    'Cleave+1': 'cleave.png',
    'Clothesline+1': 'clothesline.png',
    'Combust+1': 'combust.png',
    'Corruption+1': 'corruption.png',
    'Dark Embrace+1': 'DarkEmbrace.png',
    'Defend_R+1': 'Defend_R.png',
    'Demon Form+1': 'DemonForm.png',
    'Disarm+1': 'disarm.png',
    'Double Tap+1': 'DoubleTap.png',
    'Dropkick+1': 'dropkick.png',
    'Dual Wield+1': 'DualWield.png',
    'Entrench+1': 'entrench.png',
    'Evolve+1': 'evolve.png',
    'Exhume+1': 'exhume.png',
    'Feed+1': 'feed.png',
    'Feel No Pain+1': 'FeelNoPain.png',
    'Fiend Fire+1': 'FiendFire.png',
    'Fire Breathing+1': 'FireBreathing.png',
    'Flame Barrier+1': 'FlameBarrier.png',
    'Flex+1': 'flex.png',
    'Ghostly Armor+1': 'GhostlyArmor.png',
    'Havoc+1': 'havoc.png',
    'Headbutt+1': 'headbutt.png',
    'Heavy Blade+1': 'HeavyBlade.png',
    'Hemokinesis+1': 'hemokinesis.png',
    'Immolate+1': 'immolate.png',
    'Impervious+1': 'impervious.png',
    'Infernal Blade+1': 'InfernalBlade.png',
    'Inflame+1': 'inflame.png',
    'Intimidate+1': 'intimidate.png',
    'Iron Wave+1': 'IronWave.png',
    'Juggernaut+1': 'juggernaut.png',
    'Limit Break+1': 'LimitBreak.png',
    'Metallicize+1': 'metallicize.png',
    'Offering+1': 'offering.png',
    'Perfected Strike+1': 'PerfectedStrike.png',
    'Pommel Strike+1': 'PommelStrike.png',
    'Power Through+1': 'PowerThrough.png',
    'Pummel+1': 'pummel.png',
    'Rage+1': 'rage.png',
    'Rampage+1': 'rampage.png',
    'Reaper+1': 'reaper.png',
    'Reckless Charge+1': 'RecklessCharge.png',
    'Rupture+1': 'rupture.png',
    'Searing Blow+1': 'SearingBlow.png',
    'Second Wind+1': 'SecondWind.png',
    'Seeing Red+1': 'SeeingRed.png',
    'Sentinel+1': 'sentinel.png',
    'Sever Soul+1': 'SeverSoul.png',
    'Shockwave+1': 'shockwave.png',
    'Shrug It Off+1': 'ShrugItOff.png',
    'Spot Weakness+1': 'SpotWeakness.png',
    'Strike_R+1': 'Strike_R.png',
    'Sword Boomerang+1': 'SwordBoomerang.png',
    'Thunder Clap+1': 'thunderclap.png',
    'True Grit+1': 'TrueGrit.png',
    'Twin Strike+1': 'TwinStrike.png',
    'Uppercut+1': 'uppercut.png',
    'Warcry+1': 'warcry.png',
    'Whirlwind+1': 'whirlwind.png',
    'Wild Strike+1': 'WildStrike.png',
  },
  purple: {
    'Alpha': 'alpha.png',
    'Battle Hymn': 'battlehymn.png',
    'Blasphemy': 'blasphemy.png',
    'Bowling Bash': 'bowlingbash.png',
    'Brilliance': 'brilliance.png',
    'Calm': 'calm.png',
    'Carve Reality': 'carvereality.png',
    'Collect': 'collect.png',
    'Conclude': 'conclude.png',
    'Conjure Blade': 'conjureblade.png',
    'Consecrate': 'consecrate.png',
    'Crescendo': 'crescendo.png',
    'Crush Joints': 'crushjoints.png',
    'Cut Through Fate': 'cutthroughfate.png',
    'Deceive Reality': 'deceivereality.png',
    'Defend_P': 'defend_p.png',
    'Deus Ex Machina': 'deusexmachina.png',
    'Deva Form': 'devaform.png',
    'Devotion': 'devotion.png',
    'Empty Body': 'emptybody.png',
    'Empty Fist': 'emptyfist.png',
    'Empty Mind': 'emptymind.png',
    'Eruption': 'eruption.png',
    'Establishment': 'establishment.png',
    'Evaluate': 'evaluate.png',
    'Fasting': 'fasting.png',
    'Fear No Evil': 'fearnoevil.png',
    'Flurry of Blows': 'flurryofblows.png',
    'Follow Up': 'followup.png',
    'Foreign Influence': 'foreigninfluence.png',
    'Foresight': 'foresight.png',
    'Halt': 'halt.png',
    'Indignation': 'indignation.png',
    'Inner Peace': 'innerpeace.png',
    'Judgement': 'judgement.png',
    'Just Lucky': 'justlucky.png',
    'Lesson Learned': 'lessonlearned.png',
    'Like Water': 'likewater.png',
    'Master Reality': 'masterreality.png',
    'Meditate': 'meditate.png',
    'Mental Fortress': 'mentalfortress.png',
    'Nirvana': 'nirvana.png',
    'Omniscience': 'omniscience.png',
    'Perseverance': 'perseverance.png',
    'Pray': 'pray.png',
    'Pressure Points': 'pressurepoints.png',
    'Prostrate': 'prostrate.png',
    'Protect': 'protect.png',
    'Ragnarok': 'ragnarok.png',
    'Reach Heaven': 'reachheaven.png',
    'Rushdown': 'rushdown.png',
    'Sanctity': 'sanctity.png',
    'Sands of Time': 'sandsoftime.png',
    'Sash Whip': 'sashwhip.png',
    'Scrawl': 'scrawl.png',
    'Signature Move': 'signaturemove.png',
    'Simmering Fury': 'simmeringfury.png',
    'Spirit Shield': 'spiritshield.png',
    'Strike_P': 'strike_p.png',
    'Study': 'study.png',
    'Swivel': 'swivel.png',
    'Talk to the Hand': 'talktothehand.png',
    'Tantrum': 'tantrum.png',
    'Third Eye': 'thirdeye.png',
    'Tranquility': 'tranquility.png',
    'Unraveling': 'unraveling.png',
    'Vault': 'vault.png',
    'Vigilance': 'vigilance.png',
    'Wallop': 'wallop.png',
    'Wave of the Hand': 'waveofthehand.png',
    'Weave': 'weave.png',
    'Wheel Kick': 'wheelkick.png',
    'Windmill Strike': 'windmillstrike.png',
    'Wish': 'wish.png',
    'Worship': 'worship.png',
    'Wreath of Flame': 'wreathofflame.png',

    // UPGRADED BELOW
    'Alpha+1': 'alpha.png',
    'Battle Hymn+1': 'battlehymn.png',
    'Blasphemy+1': 'blasphemy.png',
    'Bowling Bash+1': 'bowlingbash.png',
    'Brilliance+1': 'brilliance.png',
    'Calm+1': 'calm.png',
    'Carve Reality+1': 'carvereality.png',
    'Collect+1': 'collect.png',
    'Conclude+1': 'conclude.png',
    'Conjure Blade+1': 'conjureblade.png',
    'Consecrate+1': 'consecrate.png',
    'Crescendo+1': 'crescendo.png',
    'Crush Joints+1': 'crushjoints.png',
    'Cut Through Fate+1': 'cutthroughfate.png',
    'Deceive Reality+1': 'deceivereality.png',
    'Defend_P+1': 'defend_p.png',
    'Deus Ex Machina+1': 'deusexmachina.png',
    'Deva Form+1': 'devaform.png',
    'Devotion+1': 'devotion.png',
    'Empty Body+1': 'emptybody.png',
    'Empty Fist+1': 'emptyfist.png',
    'Empty Mind+1': 'emptymind.png',
    'Eruption+1': 'eruption.png',
    'Establishment+1': 'establishment.png',
    'Evaluate+1': 'evaluate.png',
    'Fasting+1': 'fasting.png',
    'Fear No Evil+1': 'fearnoevil.png',
    'Flurry of Blows+1': 'flurryofblows.png',
    'Follow Up+1': 'followup.png',
    'Foreign Influence+1': 'foreigninfluence.png',
    'Foresight+1': 'foresight.png',
    'Halt+1': 'halt.png',
    'Indignation+1': 'indignation.png',
    'Inner Peace+1': 'innerpeace.png',
    'Judgement+1': 'judgement.png',
    'Just Lucky+1': 'justlucky.png',
    'Lesson Learned+1': 'lessonlearned.png',
    'Like Water+1': 'likewater.png',
    'Master Reality+1': 'masterreality.png',
    'Meditate+1': 'meditate.png',
    'Mental Fortress+1': 'mentalfortress.png',
    'Nirvana+1': 'nirvana.png',
    'Omniscience+1': 'omniscience.png',
    'Perseverance+1': 'perseverance.png',
    'Pray+1': 'pray.png',
    'Pressure Points+1': 'pressurepoints.png',
    'Prostrate+1': 'prostrate.png',
    'Protect+1': 'protect.png',
    'Ragnarok+1': 'ragnarok.png',
    'Reach Heaven+1': 'reachheaven.png',
    'Rushdown+1': 'rushdown.png',
    'Sanctity+1': 'sanctity.png',
    'Sands of Time+1': 'sandsoftime.png',
    'Sash Whip+1': 'sashwhip.png',
    'Scrawl+1': 'scrawl.png',
    'Signature Move+1': 'signaturemove.png',
    'Simmering Fury+1': 'simmeringfury.png',
    'Spirit Shield+1': 'spiritshield.png',
    'Strike_P+1': 'strike_p.png',
    'Study+1': 'study.png',
    'Swivel+1': 'swivel.png',
    'Talk to the Hand+1': 'talktothehand.png',
    'Tantrum+1': 'tantrum.png',
    'Third Eye+1': 'thirdeye.png',
    'Tranquility+1': 'tranquility.png',
    'Unraveling+1': 'unraveling.png',
    'Vault+1': 'vault.png',
    'Vigilance+1': 'vigilance.png',
    'Wallop+1': 'wallop.png',
    'Wave of the Hand+1': 'waveofthehand.png',
    'Weave+1': 'weave.png',
    'Wheel Kick+1': 'wheelkick.png',
    'Windmill Strike+1': 'windmillstrike.png',
    'Wish+1': 'wish.png',
    'Worship+1': 'worship.png',
    'Wreath of Flame+1': 'wreathofflame.png',
  },

  colorless: {
    'Apotheosis': 'apotheosis.png',
    'Apparition': 'apparition.png',
    'Bandage Up': 'bandageup.png',
    'Become Almigthy': 'becomealmighty.png',
    'Beta': 'beta.png',
    'Bite': 'bite.png',
    'Blind': 'blind.png',
    'Calm': 'calm.png',
    'Chrysalis': 'chrysalis.png',
    'Dark Shackles': 'darkshackles.png',
    'Deep Breath': 'deepbreath.png',
    'Discovery': 'discovery.png',
    'Dramatic Entrance': 'dramaticentrance.png',
    'Enlightenment': 'enlightenment.png',
    'Expunger': 'expunger.png',
    'Fame and Fortune': 'fameandfortune.png',
    'Finesse': 'finesse.png',
    'Flash of Steel': 'flashofsteel.png',
    'Forethought': 'forethought.png',
    'Good Instincts': 'goodinstincts.png',
    'Hand of Greed': 'handofgreed.png',
    'Impatience': 'impatience.png',
    'Insight': 'insight.png',
    'Jack of All Trades': 'jackofalltrades.png',
    'JAX': 'jax.png',
    'Live Forever': 'liveforever.png',
    'Madness': 'madness.png',
    'Magnetism': 'magnetism.png',
    'Master of Strategy': 'masterofstrategy.png',
    'Mayhem': 'mayhem.png',
    'Metamorphosis': 'metamorphosis.png',
    'Mind Blast': 'mindblast.png',
    'Miracle': 'miracle.png',
    'Omega': 'omega.png',
    'Panacea': 'panacea.png',
    'Panache': 'panache.png',
    'Panic Button': 'panicbutton.png',
    'Purity': 'purity.png',
    'Ritual Dagger': 'RitualDagger.png',
    'Sadistic Nature': 'sadisticnature.png',
    'Safety': 'safety.png',
    'Secret Technique': 'secrettechnique.png',
    'Secret Weapon': 'secretweapon.png',
    'Shiv': 'shiv.png',
    'Smite': 'smite.png',
    'Swift Strike': 'swiftstrike.png',
    'The Bomb': 'thebomb.png',
    'Thinking Ahead': 'thinkingahead.png',
    'Through Violence': 'throughviolence.png',
    'Transmutation': 'transmutation.png',
    'Trip': 'trip.png',
    'Violence': 'violence.png',
    'Wrath': 'wrath.png',

    // UPGRADED BELOW
    'Apotheosis+1': 'apotheosis.png',
    'Apparition+1': 'apparition.png',
    'Bandage Up+1': 'bandageup.png',
    'Become Almigthy+1': 'becomealmighty.png',
    'Beta+1': 'beta.png',
    'Bite+1': 'bite.png',
    'Blind+1': 'blind.png',
    'Calm+1': 'calm.png',
    'Chrysalis+1': 'chrysalis.png',
    'Dark Shackles+1': 'darkshackles.png',
    'Deep Breath+1': 'deepbreath.png',
    'Discovery+1': 'discovery.png',
    'Dramatic Entrance+1': 'dramaticentrance.png',
    'Enlightenment+1': 'enlightenment.png',
    'Expunger+1': 'expunger.png',
    'Fame and Fortune+1': 'fameandfortune.png',
    'Finesse+1': 'finesse.png',
    'Flash of Steel+1': 'flashofsteel.png',
    'Forethought+1': 'forethought.png',
    'Good Instincts+1': 'goodinstincts.png',
    'Hand of Greed+1': 'handofgreed.png',
    'Impatience+1': 'impatience.png',
    'Insight+1': 'insight.png',
    'Jack of All Trades+1': 'jackofalltrades.png',
    'JAX+1': 'jax.png',
    'Live Forever+1': 'liveforever.png',
    'Madness+1': 'madness.png',
    'Magnetism+1': 'magnetism.png',
    'Master of Strategy+1': 'masterofstrategy.png',
    'Mayhem+1': 'mayhem.png',
    'Metamorphosis+1': 'metamorphosis.png',
    'Mind Blast+1': 'mindblast.png',
    'Miracle+1': 'miracle.png',
    'Omega+1': 'omega.png',
    'Panacea+1': 'panacea.png',
    'Panache+1': 'panache.png',
    'Panic Button+1': 'panicbutton.png',
    'Purity+1': 'purity.png',
    'Ritual Dagger+1': 'RitualDagger.png',
    'Sadistic Nature+1': 'sadisticnature.png',
    'Safety+1': 'safety.png',
    'Secret Technique+1': 'secrettechnique.png',
    'Secret Weapon+1': 'secretweapon.png',
    'Shiv+1': 'shiv.png',
    'Smite+1': 'smite.png',
    'Swift Strike+1': 'swiftstrike.png',
    'The Bomb+1': 'thebomb.png',
    'Thinking Ahead+1': 'thinkingahead.png',
    'Through Violence+1': 'throughviolence.png',
    'Transmutation+1': 'transmutation.png',
    'Trip+1': 'trip.png',
    'Violence+1': 'violence.png',
    'Wrath+1': 'wrath.png',
  },
  status: {
    'Burn': 'burn.png',
    'Dazed': 'dazed.png',
    'Slimed': 'slimed.png',
    'Void': 'void.png',
    'Wound': 'wound.png',
  },
  curses: {
    'AscendersBane': 'ascendersbane.png',
    'Clumsy': 'clumsy.png',
    'CurseOfTheBell': 'curseofthebell.png',
    'Decay': 'decay.png',
    'Doubt': 'doubt.png',
    'Injury': 'injury.png',
    'Necronomicurse': 'necronomicurse.png',
    'Normality': 'normality.png',
    'Pain': 'pain.png',
    'Parasite': 'parasite.png',
    'Pride': 'pride.png',
    'Regret': 'regret.png',
    'Shame': 'shame.png',
    'Writhe': 'writhe.png',
  }
};


export default cards;